---
title: "Chapter 3"
output: html_notebook
---

# 3.6.2 Simple Linear Regression

```{r}
library(ISLR2)
library(tidyverse)
library(tidymodels)
library(ggplot2)
library(car)
```

```{r}
lm_stats1 <- lm(medv ~ lstat, data = Boston)

lm_mod <-
  linear_reg() %>%
  set_engine("lm")
lm_fit1 <-
  lm_mod %>%
  fit(medv ~ lstat, data = Boston)

summary(lm_stats1)
confint(lm_stats1)

tidy(lm_fit1)
glance(lm_fit1)
```

```{r}
conf_int_new <- predict(lm_fit1, new_data = tibble(lstat = c(5, 10, 15)), type = "conf_int")
conf_int_new
pred_int_new <- predict(lm_fit1, new_data = tibble(lstat = c(5, 10, 15)), type = "pred_int")
pred_int_new
conf_int_raw <- predict(lm_fit1, new_data = tibble(lstat = c(5, 10, 15)), type = "raw", opts = list(interval = "confidence"))
conf_int_raw
pred_int_raw <- predict(lm_fit1, new_data = tibble(lstat = c(5, 10, 15)), type = "raw", opts = list(interval = "prediction"))
pred_int_raw
```

```{r}
ggplot(Boston, aes(x = lstat, y = medv)) +
  geom_point() +
  geom_smooth(method = lm, formula = y ~ x, se = FALSE)
```

```{r}
df1_1 <-
  tibble(
    pred = predict(lm_stats1),
    resid = residuals(lm_stats1),
    cat = "raw"
  )
df1_2 <-
  tibble(
    pred = predict(lm_stats1),
    resid = rstudent(lm_stats1),
    cat = "studentized"
  )
df1 <- df1_1 %>% bind_rows(df1_2)

ggplot(df1, aes(x = pred, y = resid)) +
  geom_point() +
  facet_wrap(vars(cat), scales = "free_y")
```

```{r}
df2 <- 
  tibble(
    leverage = hatvalues(lm_stats1),
    rstudent = rstudent(lm_stats1)
  )

ggplot(df2, aes(x = leverage, y = rstudent)) +
  geom_point()
```

```{r}
lm_stats2 <- lm(medv ~ lstat + age, Boston)

summary(lm_stats2)
```

```{r}
lm_stats3 <- lm(medv ~ ., Boston)

summary(lm_stats3)
```

```{r}
vif(lm_stats3)
```

```{r}
lm_stats4 <- lm(medv ~ lstat + I(lstat^2), data = Boston)

summary(lm_stats4)
```

```{r}
anova(lm_stats1, lm_stats4)
```

```{r}
par(mfrow = c(2, 2))
plot(lm_stats4)
```

```{r}
lm_stats5 <- lm(medv ~ poly(lstat, 5), data = Boston)

summary(lm_stats5)
```





